/**
 * Demo catalogue. Prices in BDT. `art` drives the generated SVG product image
 * on the storefront; add `images: [{ url }]` to use a real photograph instead.
 */
export const CATEGORIES = [
  {
    slug: 'hijabs', name: 'Hijabs', nameBn: 'হিজাব', order: 1,
    tagline: 'Drape that holds all day', taglineBn: 'সারাদিন সুন্দর ভাঁজ',
    blurb: 'Breathable georgette, buttery jersey and premium chiffon — cut generously, hemmed by hand, and colour-matched season after season.',
    art: { shape: 'hijab', hue: 320 },
    subcategories: ['Georgette Hijab', 'Jersey Hijab', 'Chiffon Hijab', 'Instant Hijab', 'Cotton Voile', 'Silk Hijab', 'Inner Cap & Pins'],
  },
  {
    slug: 'skincare', name: 'Skin Care', nameBn: 'স্কিন কেয়ার', order: 2,
    tagline: 'Barrier-first, fragrance-light', taglineBn: 'ত্বকের সুরক্ষা আগে',
    blurb: 'Gentle actives formulated for humid weather — cleanse, hydrate and protect without stripping your skin barrier.',
    art: { shape: 'dropper', hue: 30 },
    subcategories: ['Cleanser', 'Toner', 'Serum', 'Moisturiser', 'Sunscreen', 'Mask & Lip Care', 'Body Care'],
  },
  {
    slug: 'cosmetics', name: 'Cosmetics', nameBn: 'কসমেটিকস', order: 3,
    tagline: 'Everyday colour, wedding-day payoff', taglineBn: 'প্রতিদিনের রঙ, বিয়ের দিনের জেল্লা',
    blurb: 'Long-wear formulas built for Dhaka humidity, in shades chosen for South Asian skin tones.',
    art: { shape: 'lipstick', hue: 350 },
    subcategories: ['Lips', 'Face', 'Eyes', 'Brushes & Tools', 'Gift Sets'],
  },
  {
    slug: 'hair-care', name: 'Hair Care', nameBn: 'হেয়ার কেয়ার', order: 4,
    tagline: 'For hair that lives under a scarf', taglineBn: 'হিজাবের নিচের চুলের যত্ন',
    blurb: 'Scalp-focused oils, sulphate-free washes and lightweight serums that keep length healthy under daily wrapping.',
    art: { shape: 'bottle', hue: 150 },
    subcategories: ['Hair Oil', 'Shampoo', 'Conditioner', 'Hair Serum', 'Hair Mask', 'Accessories'],
  },
  {
    slug: 'others', name: 'Others', nameBn: 'অন্যান্য', order: 5,
    tagline: 'The finishing touches', taglineBn: 'শেষ ছোঁয়া',
    blurb: 'Attar, prayer essentials, everyday jewellery and gift-ready bundles — the small things that complete the look.',
    art: { shape: 'pouch', hue: 265 },
    subcategories: ['Attar & Perfume', 'Bags & Pouches', 'Jewellery', 'Prayer Essentials', 'Abaya & Borka', 'Gift Sets'],
  },
]

const spec = (label, value) => ({ label, value })

export const PRODUCTS = [
  /* ------------------------------- HIJABS -------------------------------- */
  {
    name: 'Signature Georgette Hijab', nameBn: 'সিগনেচার জর্জেট হিজাব',
    slug: 'signature-georgette-hijab', sku: 'HJ-GEO-001',
    category: 'hijabs', subcategory: 'Georgette Hijab',
    price: 890, compareAt: 1250, costPrice: 480, stock: 60, badge: 'Bestseller',
    rating: 4.9, reviewCount: 214, soldCount: 890, featured: true,
    short: 'Weightless georgette with a soft matte fall — the one that never slips.',
    shortBn: 'হালকা জর্জেট, সারাদিন পরে থাকলেও সরে যায় না।',
    description: 'Our house georgette is woven a touch denser than the market standard, which is why it drapes without static and holds a pleat all day. Hand-hemmed on all four sides, pre-washed so the colour stays true, and cut at a generous 190 × 75 cm so you can style it open, wrapped or turban.',
    care: 'Hand wash cold with mild detergent. Do not bleach. Line dry in shade. Warm iron on reverse.',
    details: ['190 × 75 cm — generous rectangular cut', '100% premium georgette, pre-washed', 'Four-side hand-rolled hem', 'Matte finish, non-slip weave', 'Colour-fast up to 30 washes'],
    specifications: [spec('Fabric', '100% premium georgette'), spec('Size', '190 × 75 cm'), spec('Weight', '95 gsm'), spec('Finish', 'Matte, non-slip'), spec('Hem', 'Four-side hand-rolled'), spec('Origin', 'Made in Narayanganj, Bangladesh')],
    art: { shape: 'hijab', hue: 338 },
    colors: [
      { name: 'Dusty Rose', hex: '#c4787f', stock: 12 }, { name: 'Warm Sand', hex: '#d8c5ad', stock: 10 },
      { name: 'Deep Plum', hex: '#5b2a4d', stock: 9 }, { name: 'Ink Black', hex: '#1f1a1c', stock: 14 },
      { name: 'Sage', hex: '#8ea08b', stock: 8 }, { name: 'Off White', hex: '#f2ece5', stock: 7 },
    ],
    tags: ['bestseller', 'everyday'],
  },
  {
    name: 'Everyday Jersey Hijab', nameBn: 'এভরিডে জার্সি হিজাব',
    slug: 'everyday-jersey-hijab', sku: 'HJ-JER-002',
    category: 'hijabs', subcategory: 'Jersey Hijab',
    price: 750, compareAt: 950, costPrice: 400, stock: 45,
    rating: 4.8, reviewCount: 168, soldCount: 640, featured: true,
    short: 'Buttery cotton-jersey that stays put without a single pin.',
    shortBn: 'পিন ছাড়াই সেট হয়ে থাকে — নরম কটন জার্সি।',
    description: 'Four-way stretch cotton jersey with just enough weight to grip itself. Wrap it once in the morning and forget it — no pins, no re-adjusting on the bus. Our most-repurchased hijab by a wide margin.',
    care: 'Machine wash cold on gentle. Tumble dry low. Do not iron directly on fabric.',
    details: ['180 × 70 cm', '95% cotton jersey / 5% elastane', 'Four-way stretch, pin-free hold', 'Breathable — rated for 30°C+ days', 'Raw-edge finish, no fraying'],
    specifications: [spec('Fabric', '95% cotton / 5% elastane'), spec('Size', '180 × 70 cm'), spec('Stretch', 'Four-way'), spec('Closure', 'Pin-free'), spec('Machine washable', 'Yes')],
    art: { shape: 'hijab', hue: 20 },
    colors: [
      { name: 'Charcoal', hex: '#3a3538', stock: 10 }, { name: 'Camel', hex: '#b9895c', stock: 9 },
      { name: 'Mauve', hex: '#a7808f', stock: 8 }, { name: 'Navy', hex: '#2b3a55', stock: 10 },
      { name: 'Cream', hex: '#eee6da', stock: 8 },
    ],
    tags: ['everyday', 'pin-free'],
  },
  {
    name: 'Pleated Chiffon Hijab', nameBn: 'প্লিটেড শিফন হিজাব',
    slug: 'pleated-chiffon-hijab', sku: 'HJ-CHI-003',
    category: 'hijabs', subcategory: 'Chiffon Hijab',
    price: 1150, compareAt: 1500, costPrice: 620, stock: 30, badge: 'New',
    rating: 4.7, reviewCount: 76, soldCount: 180,
    short: 'Heat-set micro pleats that survive the wash. Occasion-ready.',
    description: 'Permanently heat-set micro pleating on featherlight chiffon. It packs down to nothing, shakes out crease-free, and catches light beautifully in photographs — which is why it is our go-to for mehendi and eid.',
    care: 'Hand wash cold. Do not wring. Hang to dry. Never iron — heat destroys the pleat.',
    details: ['185 × 65 cm relaxed / stretches to 90 cm', 'Permanent heat-set micro pleat', 'Featherweight chiffon, 42 gsm', 'Travel friendly — never needs ironing'],
    specifications: [spec('Fabric', 'Premium chiffon'), spec('Weight', '42 gsm'), spec('Pleat', 'Permanent heat-set'), spec('Size', '185 × 65 cm')],
    art: { shape: 'hijab', hue: 275 },
    colors: [{ name: 'Champagne', hex: '#dcc7a8', stock: 8 }, { name: 'Blush', hex: '#e6c2c0', stock: 8 }, { name: 'Emerald', hex: '#37655a', stock: 7 }, { name: 'Wine', hex: '#6e2437', stock: 7 }],
    tags: ['occasion', 'new'],
  },
  {
    name: 'Instant Slip-On Hijab', nameBn: 'ইনস্ট্যান্ট হিজাব',
    slug: 'instant-slip-on-hijab', sku: 'HJ-INS-004',
    category: 'hijabs', subcategory: 'Instant Hijab',
    price: 690, compareAt: 850, costPrice: 350, stock: 52,
    rating: 4.6, reviewCount: 141, soldCount: 520,
    short: 'Pre-sewn and ready in three seconds. Built-in cap, zero pins.',
    shortBn: 'তিন সেকেন্ডে পরা যায় — ক্যাপসহ, পিন লাগে না।',
    description: 'A fully pre-stitched hijab with an integrated jersey inner cap. Pull it over your head, adjust the drape, done. Designed for school runs, hospital shifts and anyone who has ever been late because of a pin.',
    care: 'Machine wash cold in a laundry bag. Line dry.',
    details: ['One size, integrated inner cap', 'Pre-stitched drape — no styling required', 'Soft viscose jersey blend', 'Machine washable'],
    specifications: [spec('Fabric', 'Viscose jersey blend'), spec('Fit', 'One size'), spec('Inner cap', 'Integrated'), spec('Styling time', '~3 seconds')],
    art: { shape: 'hijab', hue: 200 },
    colors: [{ name: 'Black', hex: '#1f1a1c', stock: 15 }, { name: 'Grey Mist', hex: '#9a9a9c', stock: 12 }, { name: 'Dusty Blue', hex: '#7d92a8', stock: 13 }, { name: 'Rose Taupe', hex: '#b3908c', stock: 12 }],
    tags: ['easy-wear'],
  },
  {
    name: 'Cotton Voile Shawl', slug: 'cotton-voile-shawl', sku: 'HJ-VOI-005',
    category: 'hijabs', subcategory: 'Cotton Voile',
    price: 980, compareAt: 0, costPrice: 520, stock: 26,
    rating: 4.8, reviewCount: 63, soldCount: 150,
    short: 'Airy handloom-feel cotton for the hottest months.',
    description: 'Loosely woven cotton voile with a slubby, handloom-like texture. The most breathable scarf we make — genuinely comfortable in April heat, and it softens with every wash.',
    care: 'Machine wash cold. Warm iron while slightly damp.',
    details: ['200 × 80 cm — extra long', '100% combed cotton voile', 'Slub texture, matte finish', 'Gets softer with each wash'],
    specifications: [spec('Fabric', '100% combed cotton voile'), spec('Size', '200 × 80 cm'), spec('Texture', 'Slub')],
    art: { shape: 'hijab', hue: 45 },
    colors: [{ name: 'Natural', hex: '#e8ddcb', stock: 7 }, { name: 'Terracotta', hex: '#b5714f', stock: 7 }, { name: 'Olive', hex: '#777a52', stock: 6 }, { name: 'Slate', hex: '#5f6670', stock: 6 }],
    tags: ['summer'],
  },
  {
    name: 'Mulberry Silk Hijab', slug: 'mulberry-silk-hijab', sku: 'HJ-SLK-006',
    category: 'hijabs', subcategory: 'Silk Hijab',
    price: 2450, compareAt: 3200, costPrice: 1400, stock: 14, badge: 'Luxury',
    rating: 4.9, reviewCount: 41, soldCount: 90,
    short: 'Real 19-momme mulberry silk. The one you save for the wedding.',
    description: 'Genuine grade-6A mulberry silk at 19 momme — heavy enough to drape properly rather than float. Naturally hypoallergenic and gentle on the hairline, with a lustre no synthetic satin reproduces.',
    care: 'Dry clean, or hand wash cold with silk detergent. Never wring. Dry flat away from sunlight.',
    details: ['180 × 70 cm', '100% grade-6A mulberry silk', '19 momme weight', 'Hand-rolled hem', 'Presented in a gift box'],
    specifications: [spec('Material', '100% mulberry silk, grade 6A'), spec('Weight', '19 momme'), spec('Size', '180 × 70 cm'), spec('Hem', 'Hand-rolled')],
    art: { shape: 'hijab', hue: 300 },
    colors: [{ name: 'Ivory', hex: '#f0e6d8', stock: 4 }, { name: 'Midnight', hex: '#232433', stock: 4 }, { name: 'Rose Gold', hex: '#c9899a', stock: 3 }, { name: 'Emerald', hex: '#2f5d4e', stock: 3 }],
    tags: ['luxury', 'occasion', 'gift'],
  },
  {
    name: 'Bamboo Inner Cap — Set of 3', slug: 'bamboo-inner-cap-set', sku: 'HJ-CAP-007',
    category: 'hijabs', subcategory: 'Inner Cap & Pins',
    price: 450, compareAt: 600, costPrice: 210, stock: 80,
    rating: 4.7, reviewCount: 189, soldCount: 780,
    short: 'Sweat-wicking bamboo caps that stop the hairline slip.',
    description: 'Bamboo viscose knit wicks sweat away from the hairline and grips your hijab from underneath. Wide, seam-free band that will not leave a mark on your forehead. Three neutrals per set.',
    care: 'Machine wash cold. Do not tumble dry.',
    details: ['Set of 3 — black, nude, grey', 'Bamboo viscose / spandex knit', 'Seam-free 5 cm band', 'One size, high stretch'],
    specifications: [spec('Material', 'Bamboo viscose / spandex'), spec('Pack size', '3 pieces'), spec('Band width', '5 cm')],
    art: { shape: 'pouch', hue: 25 },
    tags: ['essential'],
  },
  {
    name: 'Magnetic Hijab Pins — Set of 6', slug: 'magnetic-hijab-pin-set', sku: 'HJ-PIN-008',
    category: 'hijabs', subcategory: 'Inner Cap & Pins',
    price: 390, compareAt: 0, costPrice: 160, stock: 70,
    rating: 4.5, reviewCount: 97, soldCount: 430,
    short: 'Strong neodymium hold that never puts a hole in your chiffon.',
    description: 'Six pairs of neodymium magnetic pins in a small tin. Strong enough for jersey, gentle enough for chiffon — and no more snagged holes in expensive fabric.',
    care: 'Keep away from cards and pacemakers.',
    details: ['6 pairs in a keepsake tin', 'Neodymium N42 magnets', 'Gold, rose gold, silver, black finishes', 'Fabric-safe — no piercing'],
    specifications: [spec('Magnet grade', 'Neodymium N42'), spec('Quantity', '6 pairs'), spec('Finishes', 'Gold, rose gold, silver, black')],
    art: { shape: 'tin', hue: 40 },
    tags: ['essential'],
  },

  /* ------------------------------ SKINCARE ------------------------------- */
  {
    name: 'Niacinamide 10% Clarity Serum', nameBn: 'নায়াসিনামাইড ১০% সিরাম',
    slug: 'niacinamide-10-clarity-serum', sku: 'SK-SER-001',
    category: 'skincare', subcategory: 'Serum',
    price: 1290, compareAt: 1650, costPrice: 620, stock: 40, badge: 'Bestseller',
    rating: 4.8, reviewCount: 302, soldCount: 1120, featured: true,
    short: 'Evens tone and shrinks the look of pores in about four weeks.',
    shortBn: 'দাগ হালকা করে, চার সপ্তাহে দৃশ্যমান পরিবর্তন।',
    description: 'A lightweight water serum with 10% niacinamide and 1% zinc PCA. It calms post-acne marks, regulates oil through the afternoon, and layers cleanly under sunscreen without pilling. Fragrance-free and non-comedogenic.',
    care: 'Apply 3–4 drops to clean skin morning and night, before moisturiser. Always follow with SPF in the morning.',
    details: ['30 ml amber glass with dropper', '10% Niacinamide + 1% Zinc PCA', 'Fragrance-free, alcohol-free', 'pH 5.5 — safe for daily use', 'Dermatologically tested'],
    specifications: [spec('Key actives', '10% Niacinamide, 1% Zinc PCA'), spec('Volume', '30 ml / 50 ml'), spec('pH', '5.5'), spec('Skin type', 'All, including sensitive'), spec('Fragrance', 'None'), spec('Shelf life', '24 months unopened, 6 months after opening')],
    art: { shape: 'dropper', hue: 45 },
    sizes: [{ label: '30 ml', priceDelta: 0, stock: 25 }, { label: '50 ml', priceDelta: 620, stock: 15 }],
    tags: ['bestseller', 'acne', 'fragrance-free'],
  },
  {
    name: 'Gentle Amino Acid Cleanser', slug: 'gentle-amino-cleanser', sku: 'SK-CLN-002',
    category: 'skincare', subcategory: 'Cleanser',
    price: 850, compareAt: 0, costPrice: 390, stock: 55,
    rating: 4.9, reviewCount: 245, soldCount: 830, featured: true,
    short: 'Cleans thoroughly and leaves zero tightness behind.',
    description: 'An amino-acid surfactant gel that removes sunscreen and daily grime without stripping. pH-balanced at 5.5 so your barrier stays intact — safe to use twice a day even on reactive skin.',
    care: 'Massage a pea-sized amount onto damp skin for 30 seconds. Rinse with lukewarm water.',
    details: ['150 ml pump bottle', 'Amino acid surfactant system', 'pH 5.5, sulphate-free', 'Removes SPF without a second cleanse', 'Suitable for sensitive skin'],
    specifications: [spec('Volume', '150 ml'), spec('pH', '5.5'), spec('Surfactant', 'Amino acid based'), spec('Sulphate-free', 'Yes'), spec('Skin type', 'All, including sensitive')],
    art: { shape: 'pump', hue: 175 },
    tags: ['sensitive', 'daily'],
  },
  {
    name: 'Invisible Sunscreen SPF 50+ PA++++', nameBn: 'ইনভিজিবল সানস্ক্রিন SPF ৫০+',
    slug: 'invisible-sunscreen-spf50', sku: 'SK-SUN-003',
    category: 'skincare', subcategory: 'Sunscreen',
    price: 1450, compareAt: 1800, costPrice: 700, stock: 38, badge: "Editor's Pick",
    rating: 4.9, reviewCount: 411, soldCount: 1560, featured: true,
    short: 'No white cast, no grease. The one you will actually reapply.',
    shortBn: 'সাদা দাগ পড়ে না, চিটচিটে নয়।',
    description: 'A modern chemical filter blend that finishes matte and completely clear on deeper skin tones. Sits under makeup without pilling and does not sting the eyes — the two reasons people stop wearing sunscreen.',
    care: 'Apply two finger-lengths as the last step of your morning routine. Reapply every 3 hours outdoors.',
    details: ['50 ml squeeze tube', 'SPF 50+ / PA++++ broad spectrum', 'Zero white cast on all skin tones', 'Non-comedogenic, alcohol-free', 'Reef-friendlier filter system'],
    specifications: [spec('SPF', '50+'), spec('PA rating', 'PA++++'), spec('Volume', '50 ml'), spec('Filter type', 'Chemical, broad spectrum'), spec('Finish', 'Matte, no white cast'), spec('Makeup compatible', 'Yes')],
    art: { shape: 'tube', hue: 200 },
    tags: ['bestseller', 'daily', 'no-white-cast'],
  },
  {
    name: 'Ceramide Barrier Moisturiser', slug: 'ceramide-barrier-moisturiser', sku: 'SK-MOI-004',
    category: 'skincare', subcategory: 'Moisturiser',
    price: 1150, compareAt: 0, costPrice: 540, stock: 42,
    rating: 4.8, reviewCount: 187, soldCount: 610,
    short: 'A gel-cream that hydrates without ever feeling heavy.',
    description: 'Ceramide NP, cholesterol and fatty acids in the 3:1:1 ratio your barrier actually uses, suspended in a gel-cream base that disappears in seconds. Built for humid climates where a rich cream is unbearable.',
    care: 'Smooth over damp skin morning and night as the final step before sunscreen.',
    details: ['50 ml frosted glass jar', 'Ceramide NP + cholesterol + fatty acids', 'Gel-cream — non-greasy finish', 'Fragrance-free', 'Works over actives without irritation'],
    specifications: [spec('Volume', '50 ml'), spec('Key actives', 'Ceramide NP, cholesterol, fatty acids'), spec('Texture', 'Gel-cream'), spec('Fragrance', 'None')],
    art: { shape: 'jar', hue: 330 },
    tags: ['barrier', 'fragrance-free'],
  },
  {
    name: 'Rose & Panthenol Hydrating Toner', slug: 'rose-hydrating-toner', sku: 'SK-TON-005',
    category: 'skincare', subcategory: 'Toner',
    price: 790, compareAt: 0, costPrice: 350, stock: 48,
    rating: 4.6, reviewCount: 128, soldCount: 420,
    short: 'A calming hydration layer that preps skin for everything after.',
    description: 'Damask rose water with 3% panthenol and glycerin. Not an astringent — this is a hydrating first step that reduces redness and makes serums absorb noticeably faster.',
    care: 'Pat onto clean skin with your palms while still damp. Follow with serum.',
    details: ['200 ml bottle', 'Damask rose water base', '3% Panthenol + glycerin', 'Alcohol-free, no drying astringents'],
    specifications: [spec('Volume', '200 ml'), spec('Key actives', '3% Panthenol, glycerin'), spec('Base', 'Damask rose water'), spec('Alcohol-free', 'Yes')],
    art: { shape: 'bottle', hue: 340 },
    tags: ['hydration'],
  },
  {
    name: 'Overnight Repair Sleeping Mask', slug: 'overnight-repair-mask', sku: 'SK-MSK-006',
    category: 'skincare', subcategory: 'Mask & Lip Care',
    price: 1350, compareAt: 0, costPrice: 640, stock: 22,
    rating: 4.7, reviewCount: 94, soldCount: 290,
    short: 'Wake up with the plump, rested skin you did not earn.',
    description: 'A breathable overnight gel with squalane, madecassoside and a low-dose peptide complex. Seals in everything underneath it and works hardest during the hours your skin repairs itself.',
    care: 'Apply a thin layer as the last step, 2–3 nights per week. Rinse in the morning.',
    details: ['75 ml jar', 'Squalane + madecassoside + peptides', 'Non-occlusive — will not clog', 'Doubles as a 10-minute rescue mask'],
    specifications: [spec('Volume', '75 ml'), spec('Key actives', 'Squalane, madecassoside, peptides'), spec('Use', '2–3 nights per week')],
    art: { shape: 'jar', hue: 265 },
    tags: ['night'],
  },
  {
    name: 'Shea Lip Sleeping Balm', slug: 'lip-sleeping-balm', sku: 'SK-LIP-007',
    category: 'skincare', subcategory: 'Mask & Lip Care',
    price: 490, compareAt: 650, costPrice: 190, stock: 90,
    rating: 4.8, reviewCount: 233, soldCount: 1040,
    short: 'Fixes peeling lips overnight. Lipstick applies clean the next day.',
    description: 'Unrefined shea butter, ceramides and a whisper of vanilla in a thick balm that stays put through the night. The reliable fix for lipstick that keeps catching on dry patches.',
    care: 'Apply generously before bed. Wipe away any excess in the morning.',
    details: ['20 g tin', 'Unrefined shea + ceramide', 'Light vanilla scent', 'Vegan formula'],
    specifications: [spec('Weight', '20 g'), spec('Key actives', 'Unrefined shea butter, ceramides'), spec('Scent', 'Light vanilla'), spec('Vegan', 'Yes')],
    art: { shape: 'tin', hue: 350 },
    tags: ['gift', 'bestseller'],
  },
  {
    name: 'Vitamin C 15% Glow Serum', slug: 'vitamin-c-glow-serum', sku: 'SK-SER-008',
    category: 'skincare', subcategory: 'Serum',
    price: 1590, compareAt: 1990, costPrice: 780, stock: 32, badge: 'New',
    rating: 4.7, reviewCount: 88, soldCount: 240,
    short: 'Stabilised L-ascorbic acid that actually stays potent in the bottle.',
    description: '15% L-ascorbic acid with ferulic acid and vitamin E in an airless pump — the packaging matters as much as the formula, because vitamin C oxidises the moment it meets air and light.',
    care: 'Apply 3 drops in the morning before moisturiser and sunscreen. Introduce slowly if you are new to vitamin C.',
    details: ['30 ml airless pump', '15% L-ascorbic acid + 0.5% ferulic', 'Vitamin E for stability', 'Amber UV-blocking bottle'],
    specifications: [spec('Volume', '30 ml'), spec('Key actives', '15% L-ascorbic acid, ferulic acid, vitamin E'), spec('pH', '3.2'), spec('Packaging', 'Airless pump, UV-blocking')],
    art: { shape: 'dropper', hue: 35 },
    tags: ['new', 'brightening'],
  },
  {
    name: 'Oat Body Butter', slug: 'oat-body-butter', sku: 'SK-BOD-009',
    category: 'skincare', subcategory: 'Body Care',
    price: 890, compareAt: 1100, costPrice: 400, stock: 44,
    rating: 4.6, reviewCount: 76, soldCount: 210,
    short: 'Sinks in fast enough to dress straight after.',
    description: 'Colloidal oatmeal, shea and squalane whipped into a butter that absorbs in under a minute. Made for elbows, knees and the dry patches that a lotion never quite fixes.',
    care: 'Apply to damp skin after showering.',
    details: ['200 ml jar', 'Colloidal oatmeal + shea + squalane', 'Fragrance-free', 'Absorbs in under 60 seconds'],
    specifications: [spec('Volume', '200 ml'), spec('Key actives', 'Colloidal oatmeal, shea butter, squalane'), spec('Fragrance', 'None')],
    art: { shape: 'jar', hue: 40 },
    tags: ['body'],
  },

  /* ------------------------------ COSMETICS ------------------------------ */
  {
    name: 'Velvet Matte Lipstick', nameBn: 'ভেলভেট ম্যাট লিপস্টিক',
    slug: 'velvet-matte-lipstick', sku: 'CS-LIP-001',
    category: 'cosmetics', subcategory: 'Lips',
    price: 890, compareAt: 1100, costPrice: 380, stock: 65, badge: 'Bestseller',
    rating: 4.8, reviewCount: 356, soldCount: 1380, featured: true,
    short: 'Eight hours of colour that never turns your lips to paper.',
    shortBn: 'আট ঘণ্টা টেকে, ঠোঁট শুকায় না।',
    description: 'A cushiony matte that sets down soft, not flat. Full opacity in one pass, survives tea and a full meal, and stays comfortable because we built it on an emollient base instead of pure alcohol.',
    care: 'Line lips first for the sharpest edge. Blot once and reapply for maximum wear.',
    details: ['3.8 g bullet, magnetic cap', '8-hour transfer-resistant wear', 'One-swipe full coverage', 'Vitamin E + jojoba base', 'Paraben-free, not tested on animals'],
    specifications: [spec('Weight', '3.8 g'), spec('Finish', 'Velvet matte'), spec('Wear time', '8 hours'), spec('Coverage', 'Full, one swipe'), spec('Cruelty-free', 'Yes'), spec('Paraben-free', 'Yes')],
    art: { shape: 'lipstick', hue: 350 },
    colors: [
      { name: 'Rosewood', hex: '#9c5560', stock: 12 }, { name: 'Brick', hex: '#a8412f', stock: 11 },
      { name: 'Mulberry', hex: '#6f2a45', stock: 10 }, { name: 'Nude Chai', hex: '#b07f6b', stock: 12 },
      { name: 'Classic Red', hex: '#b81e35', stock: 11 }, { name: 'Dusty Pink', hex: '#c47c88', stock: 9 },
    ],
    tags: ['bestseller', 'long-wear'],
  },
  {
    name: 'Weightless Skin Tint Foundation', slug: 'skin-tint-foundation', sku: 'CS-FND-002',
    category: 'cosmetics', subcategory: 'Face',
    price: 1590, compareAt: 0, costPrice: 720, stock: 34,
    rating: 4.6, reviewCount: 178, soldCount: 490,
    short: 'Buildable coverage in twelve shades matched to South Asian undertones.',
    description: 'A breathable serum-foundation with niacinamide and SPF 20. Twelve shades developed specifically for warm, olive and deep South Asian undertones — the range most global brands skip.',
    care: 'Apply with damp sponge for skin-like finish, or a brush for more coverage.',
    details: ['30 ml pump bottle', '12 shades, warm/neutral/olive undertones', 'SPF 20 + niacinamide', 'Buildable light-to-medium coverage', 'Oil-free, non-comedogenic'],
    specifications: [spec('Volume', '30 ml'), spec('SPF', '20'), spec('Coverage', 'Light to medium, buildable'), spec('Shade range', '12 shades'), spec('Oil-free', 'Yes')],
    art: { shape: 'pump', hue: 28 },
    colors: [
      { name: '110 Porcelain', hex: '#f0d5c0', stock: 5 }, { name: '210 Sand', hex: '#e3bd9d', stock: 6 },
      { name: '320 Honey', hex: '#cf9f76', stock: 7 }, { name: '410 Almond', hex: '#b1794f', stock: 6 },
      { name: '520 Chestnut', hex: '#8c5a38', stock: 5 }, { name: '620 Espresso', hex: '#5f3b26', stock: 5 },
    ],
    tags: ['inclusive-shades'],
  },
  {
    name: 'Smudge-Proof Kajal', nameBn: 'স্মাজ-প্রুফ কাজল',
    slug: 'smudge-proof-kajal', sku: 'CS-EYE-003',
    category: 'cosmetics', subcategory: 'Eyes',
    price: 450, compareAt: 590, costPrice: 170, stock: 88,
    rating: 4.7, reviewCount: 289, soldCount: 1250, featured: true,
    short: 'Blackest black waterline kajal that survives a Dhaka summer.',
    shortBn: 'ঘামেও ছড়ায় না — গাঢ় কালো কাজল।',
    description: 'A waterproof gel-crayon that sets in 20 seconds and then simply does not move — no grey shadow under the eye at 4 pm. Ophthalmologist-tested and safe for contact lens wearers.',
    care: 'Remove with an oil-based cleanser or micellar water.',
    details: ['0.35 g retractable twist-up', '12-hour waterproof, smudge-proof wear', 'Intense one-stroke pigment', 'Ophthalmologist tested, lens-safe'],
    specifications: [spec('Weight', '0.35 g'), spec('Wear time', '12 hours'), spec('Waterproof', 'Yes'), spec('Lens safe', 'Yes'), spec('Applicator', 'Retractable twist-up')],
    art: { shape: 'pencil', hue: 260 },
    tags: ['bestseller', 'waterproof'],
  },
  {
    name: 'Volumising Fibre Mascara', slug: 'volumising-mascara', sku: 'CS-EYE-004',
    category: 'cosmetics', subcategory: 'Eyes',
    price: 950, compareAt: 0, costPrice: 420, stock: 41,
    rating: 4.5, reviewCount: 142, soldCount: 380,
    short: 'Lash-extension volume with a brush that never clumps.',
    description: 'Micro-fibres grip each lash and build length coat over coat, while the hourglass brush separates as it goes. Tubing formula — it slides off with warm water instead of scrubbing.',
    care: 'Warm water and gentle pressure removes the tubes intact. No rubbing needed.',
    details: ['9 ml tube', 'Tubing formula — warm water removal', 'Micro-fibre length building', 'Hourglass separating brush', 'Smudge-proof, humidity resistant'],
    specifications: [spec('Volume', '9 ml'), spec('Formula', 'Tubing'), spec('Removal', 'Warm water'), spec('Brush', 'Hourglass separating')],
    art: { shape: 'mascara', hue: 250 },
    tags: ['eyes'],
  },
  {
    name: 'Silk Finish Compact Powder', slug: 'silk-compact-powder', sku: 'CS-FCE-005',
    category: 'cosmetics', subcategory: 'Face',
    price: 790, compareAt: 0, costPrice: 340, stock: 50,
    rating: 4.6, reviewCount: 156, soldCount: 470,
    short: 'Blurs shine without ever going cakey on top of foundation.',
    description: 'Finely milled silica and rice powder with a soft-focus finish. Controls shine for four hours and photographs without flashback — safe for weddings and flash-heavy events.',
    care: 'Press — do not sweep — into the T-zone for the longest wear.',
    details: ['9 g compact with mirror + puff', 'No flashback in photographs', '4-hour shine control', 'Six shades, translucent to deep'],
    specifications: [spec('Weight', '9 g'), spec('Finish', 'Soft-focus matte'), spec('Flashback', 'None'), spec('Includes', 'Mirror and puff')],
    art: { shape: 'compact', hue: 32 },
    colors: [{ name: 'Translucent', hex: '#efe0d3', stock: 14 }, { name: 'Ivory', hex: '#e8cfb6', stock: 12 }, { name: 'Beige', hex: '#d8b391', stock: 12 }, { name: 'Deep', hex: '#9c6a45', stock: 12 }],
    tags: ['face'],
  },
  {
    name: 'Silk Blush & Highlight Duo', slug: 'silk-blush-duo', sku: 'CS-FCE-006',
    category: 'cosmetics', subcategory: 'Face',
    price: 1090, compareAt: 0, costPrice: 480, stock: 28, badge: 'New',
    rating: 4.7, reviewCount: 68, soldCount: 190,
    short: 'A flush and a glow that read as skin, not makeup.',
    description: 'A talc-free pressed blush paired with a finely milled highlighter that catches light without glitter fallout. Blends with fingers on the go — no brush required.',
    care: 'Tap off excess and build in thin layers.',
    details: ['8 g dual pan', 'Talc-free, silica-cushioned', 'Blends with fingertips', 'Four curated pairings'],
    specifications: [spec('Weight', '8 g'), spec('Talc-free', 'Yes'), spec('Format', 'Dual pan')],
    art: { shape: 'compact', hue: 348 },
    colors: [{ name: 'Rose Quartz', hex: '#cf8f96', stock: 7 }, { name: 'Terracotta', hex: '#b96f52', stock: 7 }, { name: 'Berry', hex: '#8d4359', stock: 7 }, { name: 'Peach', hex: '#dd9a7c', stock: 7 }],
    tags: ['new'],
  },
  {
    name: 'Vegan Brush Set — 8 Piece', slug: 'vegan-brush-set', sku: 'CS-TLS-007',
    category: 'cosmetics', subcategory: 'Brushes & Tools',
    price: 1890, compareAt: 2400, costPrice: 850, stock: 20,
    rating: 4.8, reviewCount: 112, soldCount: 260,
    short: 'Eight brushes that cover a full face, in a magnetic travel case.',
    description: 'Densely packed synthetic bristles that pick up pigment like natural hair but wash clean in seconds. Eight essentials — foundation, concealer, powder, blush, blending, shader, liner, brow — in a magnetic-close case.',
    care: 'Wash weekly with mild soap. Dry flat, bristles pointing down.',
    details: ['8 brushes + magnetic case', 'Cruelty-free synthetic bristles', 'Aluminium ferrules, weighted handles', 'Shed-resistant construction'],
    specifications: [spec('Pieces', '8 brushes'), spec('Bristles', 'Synthetic, cruelty-free'), spec('Ferrule', 'Aluminium'), spec('Case', 'Magnetic close')],
    art: { shape: 'brush', hue: 20 },
    tags: ['gift', 'tools'],
  },
  {
    name: 'Bridal Glam Gift Set', nameBn: 'ব্রাইডাল গিফট সেট',
    slug: 'bridal-glam-gift-set', sku: 'CS-GFT-008',
    category: 'cosmetics', subcategory: 'Gift Sets',
    price: 3490, compareAt: 4600, costPrice: 1600, stock: 14, badge: 'Gift',
    rating: 4.9, reviewCount: 57, soldCount: 120,
    short: 'Five hero products in a keepsake box, wrapped and ready.',
    description: 'Velvet Matte Lipstick in Mulberry, Smudge-Proof Kajal, Silk Compact Powder, Blush Duo in Rose Quartz and the Lip Sleeping Balm — packed in a rigid keepsake box with a hand-tied ribbon and a blank gift card.',
    care: 'Store the box away from direct sunlight.',
    details: ['5 full-size products', 'Rigid keepsake box + ribbon', 'Handwritten gift note available at checkout', 'Save ৳1,110 versus buying separately'],
    specifications: [spec('Contents', '5 full-size products'), spec('Packaging', 'Rigid keepsake box with ribbon'), spec('Saving', '৳1,110 vs individual')],
    art: { shape: 'giftbox', hue: 335 },
    tags: ['gift', 'value'],
  },

  /* ------------------------------ HAIR CARE ------------------------------ */
  {
    name: 'Rosemary Scalp Growth Oil', nameBn: 'রোজমেরি স্ক্যাল্প অয়েল',
    slug: 'rosemary-scalp-growth-oil', sku: 'HC-OIL-001',
    category: 'hair-care', subcategory: 'Hair Oil',
    price: 990, compareAt: 1300, costPrice: 420, stock: 58, badge: 'Bestseller',
    rating: 4.9, reviewCount: 398, soldCount: 1490, featured: true,
    short: 'Cold-pressed oils and rosemary for thinning edges and covered hair.',
    shortBn: 'চুল পড়া কমায়, হিজাবের নিচের স্ক্যাল্পের জন্য।',
    description: 'Rosemary, castor, black seed and grapeseed in a non-greasy blend built for scalps that spend the day under a scarf. The nozzle applicator parts hair and delivers oil where it matters, without soaking the length.',
    care: 'Massage into the scalp 2–3 times weekly. Leave 2 hours or overnight, then shampoo.',
    details: ['100 ml with precision scalp nozzle', 'Rosemary + castor + black seed + grapeseed', 'Cold-pressed, no mineral oil', 'Non-greasy — washes out in one shampoo', 'Safe for coloured and treated hair'],
    specifications: [spec('Volume', '100 ml / 200 ml'), spec('Key oils', 'Rosemary, castor, black seed, grapeseed'), spec('Extraction', 'Cold-pressed'), spec('Mineral oil', 'None'), spec('Applicator', 'Precision scalp nozzle')],
    art: { shape: 'dropper', hue: 130 },
    sizes: [{ label: '100 ml', priceDelta: 0, stock: 38 }, { label: '200 ml', priceDelta: 700, stock: 20 }],
    tags: ['bestseller', 'hair-fall'],
  },
  {
    name: 'Sulphate-Free Strengthening Shampoo', slug: 'sulphate-free-shampoo', sku: 'HC-SHP-002',
    category: 'hair-care', subcategory: 'Shampoo',
    price: 890, compareAt: 0, costPrice: 390, stock: 46,
    rating: 4.7, reviewCount: 204, soldCount: 620,
    short: 'Lathers properly without stripping colour or moisture.',
    description: 'A gentle glucoside cleansing system with hydrolysed rice protein and biotin. Rich enough to actually feel clean, mild enough for daily washing when your hair is covered every day.',
    care: 'Massage into the scalp, not the length. Rinse thoroughly and follow with conditioner.',
    details: ['300 ml pump bottle', 'Sulphate-free, silicone-free', 'Hydrolysed rice protein + biotin', 'Colour-safe, pH 5.0', 'Safe for daily use'],
    specifications: [spec('Volume', '300 ml'), spec('pH', '5.0'), spec('Sulphate-free', 'Yes'), spec('Silicone-free', 'Yes'), spec('Key actives', 'Hydrolysed rice protein, biotin')],
    art: { shape: 'pump', hue: 145 },
    tags: ['daily'],
  },
  {
    name: 'Detangling Slip Conditioner', slug: 'slip-conditioner', sku: 'HC-CON-003',
    category: 'hair-care', subcategory: 'Conditioner',
    price: 890, compareAt: 0, costPrice: 390, stock: 44,
    rating: 4.7, reviewCount: 163, soldCount: 540,
    short: 'Comb glides straight through. No weight, no flat roots.',
    description: 'Behentrimonium and shea give enough slip to detangle waist-length hair with your fingers, while staying light enough that roots do not go flat by evening.',
    care: 'Apply from mid-length to ends. Leave 2 minutes and rinse cool.',
    details: ['300 ml pump bottle', 'Behentrimonium + shea butter', 'Detangles without weighing down', 'Silicone-free formula'],
    specifications: [spec('Volume', '300 ml'), spec('Key actives', 'Behentrimonium, shea butter'), spec('Silicone-free', 'Yes')],
    art: { shape: 'pump', hue: 165 },
    tags: ['daily'],
  },
  {
    name: 'Heat Shield Hair Serum', slug: 'heat-shield-hair-serum', sku: 'HC-SER-004',
    category: 'hair-care', subcategory: 'Hair Serum',
    price: 750, compareAt: 0, costPrice: 320, stock: 52,
    rating: 4.6, reviewCount: 121, soldCount: 400,
    short: 'Tames frizz and protects to 220°C without a greasy film.',
    description: 'A dry-touch serum with argan oil and heat-activated polymers. Smooths flyaways in humidity and gives real thermal protection before straightening — two pumps for mid-length hair.',
    care: 'Two pumps through damp mid-lengths and ends before heat styling.',
    details: ['50 ml pump', 'Thermal protection to 220°C', 'Argan oil + vitamin E', 'Dry-touch, non-greasy finish'],
    specifications: [spec('Volume', '50 ml'), spec('Heat protection', 'Up to 220°C'), spec('Key oils', 'Argan, vitamin E'), spec('Finish', 'Dry-touch')],
    art: { shape: 'bottle', hue: 120 },
    tags: ['styling'],
  },
  {
    name: 'Protein Repair Hair Mask', slug: 'protein-repair-hair-mask', sku: 'HC-MSK-005',
    category: 'hair-care', subcategory: 'Hair Mask',
    price: 1190, compareAt: 1450, costPrice: 520, stock: 30,
    rating: 4.8, reviewCount: 137, soldCount: 340,
    short: 'One weekly treatment for hair that has been bleached or over-styled.',
    description: 'Keratin peptides and hyaluronic acid rebuild damaged hair from the inside while shea seals the cuticle. Noticeably less breakage on the comb after three uses.',
    care: 'Apply to clean damp hair, leave 10 minutes, rinse. Use once a week — protein overload is real.',
    details: ['250 g jar', 'Keratin peptides + hyaluronic acid', '10-minute weekly treatment', 'Safe for bleached and coloured hair'],
    specifications: [spec('Weight', '250 g'), spec('Key actives', 'Keratin peptides, hyaluronic acid, shea'), spec('Treatment time', '10 minutes'), spec('Frequency', 'Once weekly')],
    art: { shape: 'jar', hue: 155 },
    tags: ['repair'],
  },
  {
    name: 'Satin Scrunchie Set — 6 Piece', slug: 'satin-scrunchie-set', sku: 'HC-ACC-006',
    category: 'hair-care', subcategory: 'Accessories',
    price: 420, compareAt: 0, costPrice: 150, stock: 95,
    rating: 4.7, reviewCount: 176, soldCount: 810,
    short: 'Satin that never leaves a crease or snaps a strand.',
    description: 'Six mulberry-look satin scrunchies on soft elastic. No metal, no dents, no breakage at the tie point — and they sit smoothly under a hijab without creating a bump.',
    care: 'Hand wash cold, air dry.',
    details: ['Set of 6 neutrals', 'Satin, snag-free', 'No metal fastenings', 'Hijab-friendly low profile'],
    specifications: [spec('Pack size', '6 pieces'), spec('Material', 'Satin'), spec('Metal-free', 'Yes')],
    art: { shape: 'pouch', hue: 300 },
    tags: ['accessory', 'gift'],
  },
  {
    name: 'Neem Wood Detangling Comb', slug: 'wide-tooth-detangle-comb', sku: 'HC-ACC-007',
    category: 'hair-care', subcategory: 'Accessories',
    price: 380, compareAt: 0, costPrice: 130, stock: 62,
    rating: 4.6, reviewCount: 88, soldCount: 350,
    short: 'Hand-cut neem wood — anti-static and kind to a wet scalp.',
    description: 'Hand-finished neem wood with rounded, wide-set teeth. Naturally anti-static, so it smooths rather than frizzes, and gentle enough to use on wet hair without snapping it.',
    care: 'Wipe clean with a dry cloth. Never soak in water.',
    details: ['20 cm hand-cut neem wood', 'Wide-set rounded teeth', 'Anti-static', 'Safe on wet hair'],
    specifications: [spec('Length', '20 cm'), spec('Material', 'Neem wood'), spec('Tooth spacing', 'Wide-set')],
    art: { shape: 'comb', hue: 35 },
    tags: ['accessory'],
  },
  {
    name: 'Onion & Bhringraj Hair Tonic', slug: 'onion-bhringraj-tonic', sku: 'HC-TON-008',
    category: 'hair-care', subcategory: 'Hair Serum',
    price: 850, compareAt: 1050, costPrice: 360, stock: 40, badge: 'New',
    rating: 4.6, reviewCount: 64, soldCount: 180,
    short: 'A leave-in scalp tonic for shedding — without the onion smell.',
    description: 'Red onion extract and bhringraj in a water-light leave-in that absorbs in seconds. We deodorise the onion extract, so you get the sulphur benefits without smelling like dinner.',
    care: 'Spray on the scalp daily and massage in. Do not rinse.',
    details: ['100 ml spray', 'Red onion + bhringraj + caffeine', 'Deodorised — no onion smell', 'Leave-in, no rinsing'],
    specifications: [spec('Volume', '100 ml'), spec('Key actives', 'Red onion extract, bhringraj, caffeine'), spec('Format', 'Leave-in spray')],
    art: { shape: 'bottle', hue: 140 },
    tags: ['new', 'hair-fall'],
  },

  /* -------------------------------- OTHERS ------------------------------- */
  {
    name: 'Oud & Rose Attar', nameBn: 'উদ ও গোলাপ আতর',
    slug: 'oud-rose-attar', sku: 'OT-ATR-001',
    category: 'others', subcategory: 'Attar & Perfume',
    price: 1650, compareAt: 2100, costPrice: 700, stock: 25, badge: 'Bestseller',
    rating: 4.9, reviewCount: 176, soldCount: 520, featured: true,
    short: 'Alcohol-free oil attar with genuine six-hour depth.',
    shortBn: 'অ্যালকোহল-মুক্ত আতর, ছয় ঘণ্টা স্থায়ী।',
    description: 'Cambodian oud softened with Taif rose in a jojoba oil base. Alcohol-free, so it warms with your skin rather than flashing off — one dab on each wrist carries through the evening.',
    care: 'Roll onto pulse points. Do not rub — it breaks the top notes.',
    details: ['12 ml roll-on glass bottle', 'Alcohol-free oil concentrate', 'Cambodian oud + Taif rose', '6–8 hour longevity', 'Prayer-appropriate'],
    specifications: [spec('Volume', '12 ml'), spec('Base', 'Jojoba oil'), spec('Alcohol-free', 'Yes'), spec('Longevity', '6–8 hours'), spec('Notes', 'Cambodian oud, Taif rose')],
    art: { shape: 'attar', hue: 285 },
    tags: ['bestseller', 'gift'],
  },
  {
    name: 'Padded Velvet Prayer Mat', nameBn: 'ভেলভেট জায়নামাজ',
    slug: 'velvet-prayer-mat', sku: 'OT-PRY-002',
    category: 'others', subcategory: 'Prayer Essentials',
    price: 1450, compareAt: 0, costPrice: 680, stock: 18,
    rating: 4.8, reviewCount: 92, soldCount: 230,
    short: 'Memory-foam padding where your knees and forehead land.',
    description: 'A dense velvet mat with targeted memory-foam padding at the knee and forehead points, and a non-slip backing that stays put on tile. Folds into its own carry strap.',
    care: 'Spot clean only. Do not machine wash.',
    details: ['110 × 65 cm', 'Memory foam at knee + forehead', 'Non-slip rubberised backing', 'Folds with attached carry strap'],
    specifications: [spec('Size', '110 × 65 cm'), spec('Padding', 'Memory foam'), spec('Backing', 'Non-slip rubberised')],
    art: { shape: 'mat', hue: 250 },
    colors: [{ name: 'Deep Teal', hex: '#2f5d5e', stock: 6 }, { name: 'Plum', hex: '#5b2a4d', stock: 6 }, { name: 'Charcoal', hex: '#3a3538', stock: 6 }],
    tags: ['prayer'],
  },
  {
    name: 'Quilted Crossbody Bag', slug: 'quilted-crossbody-bag', sku: 'OT-BAG-003',
    category: 'others', subcategory: 'Bags & Pouches',
    price: 2290, compareAt: 2900, costPrice: 1050, stock: 16, badge: 'New',
    rating: 4.7, reviewCount: 64, soldCount: 140,
    short: 'Vegan leather, gold hardware, fits a phone and a full face of makeup.',
    description: 'A structured quilted crossbody in soft vegan leather with brushed gold hardware. Two interior slots plus a zip pocket, and an adjustable chain-and-leather strap you can wear short or long.',
    care: 'Wipe with a damp cloth. Store stuffed in the dust bag.',
    details: ['24 × 16 × 7 cm', 'Vegan leather, brushed gold hardware', 'Adjustable chain + leather strap', 'Interior zip + 2 card slots'],
    specifications: [spec('Dimensions', '24 × 16 × 7 cm'), spec('Material', 'Vegan leather'), spec('Hardware', 'Brushed gold'), spec('Strap', 'Adjustable chain and leather')],
    art: { shape: 'bag', hue: 15 },
    colors: [{ name: 'Black', hex: '#211d1f', stock: 6 }, { name: 'Cream', hex: '#e6dbcb', stock: 5 }, { name: 'Mocha', hex: '#7a5747', stock: 5 }],
    tags: ['new', 'accessory'],
  },
  {
    name: 'Freshwater Pearl Drop Earrings', slug: 'pearl-drop-earrings', sku: 'OT-JWL-004',
    category: 'others', subcategory: 'Jewellery',
    price: 1290, compareAt: 0, costPrice: 540, stock: 22,
    rating: 4.7, reviewCount: 81, soldCount: 200,
    short: 'Real freshwater pearls on hypoallergenic gold-filled hooks.',
    description: 'Genuine baroque freshwater pearls suspended from 14k gold-filled hooks. Light enough to wear all day and nickel-free, so they will not irritate sensitive ears.',
    care: 'Put on after perfume. Wipe with a soft cloth after wear.',
    details: ['Genuine baroque freshwater pearl', '14k gold-filled hooks', 'Nickel-free, hypoallergenic', 'Arrives in a gift pouch'],
    specifications: [spec('Stone', 'Baroque freshwater pearl'), spec('Metal', '14k gold-filled'), spec('Nickel-free', 'Yes')],
    art: { shape: 'jewel', hue: 45 },
    tags: ['gift', 'jewellery'],
  },
  {
    name: 'Travel Hijab Organiser', slug: 'travel-hijab-organiser', sku: 'OT-BAG-005',
    category: 'others', subcategory: 'Bags & Pouches',
    price: 890, compareAt: 0, costPrice: 380, stock: 34,
    rating: 4.6, reviewCount: 73, soldCount: 190,
    short: 'Rolls eight hijabs crease-free into a suitcase-sized pouch.',
    description: 'Eight padded roll-slots keep hijabs crease-free and separated in a suitcase, with a mesh top so you can see what you packed. A zip end pocket holds caps and pins.',
    care: 'Wipe clean with a damp cloth.',
    details: ['8 padded roll slots', 'Mesh visibility panel', 'Zip pocket for caps and pins', 'Water-resistant lining'],
    specifications: [spec('Capacity', '8 hijabs'), spec('Lining', 'Water-resistant'), spec('Extra', 'Zip pocket for caps and pins')],
    art: { shape: 'pouch', hue: 200 },
    tags: ['travel'],
  },
  {
    name: 'Everyday Nida Abaya', nameBn: 'নিদা আবায়া',
    slug: 'everyday-nida-abaya', sku: 'OT-ABY-006',
    category: 'others', subcategory: 'Abaya & Borka',
    price: 2890, compareAt: 3600, costPrice: 1350, stock: 20,
    rating: 4.8, reviewCount: 96, soldCount: 260,
    short: 'Korean Nida that holds its shape and never turns see-through.',
    shortBn: 'কোরিয়ান নিদা কাপড় — ভেতরের কিছু দেখা যায় না।',
    description: 'Heavy Korean Nida in a straight cut with side pockets and a full front zip. Opaque under Dhaka sun, wrinkle-resistant enough to travel in, and cut long in the sleeve so it stays put when you raise your arms.',
    care: 'Machine wash cold. Hang dry. Warm iron if needed.',
    details: ['Sizes 52–60 (chest 38–48 in)', 'Korean Nida fabric, fully opaque', 'Side pockets + full front zip', 'Wrinkle resistant', 'Matching hijab included'],
    specifications: [spec('Fabric', 'Korean Nida'), spec('Cut', 'Straight with side pockets'), spec('Closure', 'Full front zip'), spec('Includes', 'Matching hijab')],
    art: { shape: 'abaya', hue: 240 },
    sizes: [
      { label: '52', priceDelta: 0, stock: 4 }, { label: '54', priceDelta: 0, stock: 5 },
      { label: '56', priceDelta: 0, stock: 5 }, { label: '58', priceDelta: 100, stock: 3 },
      { label: '60', priceDelta: 100, stock: 3 },
    ],
    colors: [{ name: 'Black', hex: '#1c1a1d', stock: 12 }, { name: 'Navy', hex: '#2a3247', stock: 4 }, { name: 'Maroon', hex: '#5d2630', stock: 4 }],
    tags: ['abaya', 'everyday'],
  },
  {
    name: 'Self-Care Sunday Bundle', slug: 'self-care-sunday-bundle', sku: 'OT-GFT-007',
    category: 'others', subcategory: 'Gift Sets',
    price: 2790, compareAt: 3650, costPrice: 1250, stock: 12, badge: 'Gift',
    rating: 4.9, reviewCount: 48, soldCount: 110,
    short: 'A hijab, a hair mask, a sleeping mask and a lip balm in one box.',
    description: 'Our most-gifted bundle: the Everyday Jersey Hijab, Protein Repair Hair Mask, Overnight Repair Sleeping Mask and Shea Lip Sleeping Balm, boxed with tissue and a blank card.',
    care: 'See individual products for care instructions.',
    details: ['4 full-size products', 'Gift box, tissue and blank card', 'Save ৳860 versus buying separately', 'Colour of the hijab chosen at checkout'],
    specifications: [spec('Contents', '4 full-size products'), spec('Packaging', 'Gift box with tissue and card'), spec('Saving', '৳860 vs individual')],
    art: { shape: 'giftbox', hue: 270 },
    tags: ['gift', 'value'],
  },
  {
    name: 'Ramadan Essentials Box', slug: 'ramadan-essentials-box', sku: 'OT-GFT-008',
    category: 'others', subcategory: 'Gift Sets',
    price: 3290, compareAt: 4200, costPrice: 1500, stock: 15, badge: 'Gift',
    rating: 4.8, reviewCount: 39, soldCount: 85,
    short: 'Prayer mat, attar, tasbih and a jersey hijab — boxed for gifting.',
    description: 'Everything for the month in one box: the Padded Velvet Prayer Mat, Oud & Rose Attar, a crystal tasbih and the Everyday Jersey Hijab. Our most-gifted set through Ramadan and Eid.',
    care: 'See individual products for care instructions.',
    details: ['4 items in a rigid gift box', 'Includes crystal tasbih', 'Handwritten card available', 'Save ৳910 versus buying separately'],
    specifications: [spec('Contents', 'Prayer mat, attar, tasbih, hijab'), spec('Packaging', 'Rigid gift box'), spec('Saving', '৳910 vs individual')],
    art: { shape: 'giftbox', hue: 250 },
    tags: ['gift', 'value', 'ramadan'],
  },
]
